"""jobs applications saved searches

Revision ID: e557283fb2ab
Revises: 
Create Date: 2026-09-25 23:09:15.366996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e557283fb2ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('company', sa.String(length=512), nullable=False),
    sa.Column('location', sa.String(length=256), nullable=False),
    sa.Column('district', sa.String(length=128), nullable=False),
    sa.Column('is_remote', sa.Boolean(), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('salary', sa.String(length=256), nullable=False),
    sa.Column('posted_date', sa.String(length=64), nullable=False),
    sa.Column('sectors', sa.JSON(), nullable=False),
    sa.Column('job_function', sa.String(length=32), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_active_deadline', 'jobs', ['is_active', 'deadline'], unique=False)
    op.create_index(op.f('ix_jobs_deadline'), 'jobs', ['deadline'], unique=False)
    op.create_index(op.f('ix_jobs_district'), 'jobs', ['district'], unique=False)
    op.create_index(op.f('ix_jobs_first_seen_at'), 'jobs', ['first_seen_at'], unique=False)
    op.create_index(op.f('ix_jobs_is_active'), 'jobs', ['is_active'], unique=False)
    op.create_index(op.f('ix_jobs_is_remote'), 'jobs', ['is_remote'], unique=False)
    op.create_index(op.f('ix_jobs_job_function'), 'jobs', ['job_function'], unique=False)
    op.create_index(op.f('ix_jobs_source'), 'jobs', ['source'], unique=False)
    op.create_index('ix_jobs_source_first_seen', 'jobs', ['source', 'first_seen_at'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('tracking_id', sa.String(length=128), nullable=True),
    sa.Column('fee_paid', sa.Boolean(), nullable=False),
    sa.Column('admit_downloaded', sa.Boolean(), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('job_snapshot', sa.JSON(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_index('ix_applications_user_status', 'applications', ['user_id', 'status'], unique=False)
    op.create_table('notification_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notif_user_job_kind', 'notification_logs', ['user_id', 'job_id', 'kind'], unique=False)
    op.create_index(op.f('ix_notification_logs_user_id'), 'notification_logs', ['user_id'], unique=False)
    op.create_table('saved_searches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('notify_telegram', sa.Boolean(), nullable=False),
    sa.Column('notify_email', sa.Boolean(), nullable=False),
    sa.Column('last_notified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_searches_user_id'), 'saved_searches', ['user_id'], unique=False)
    op.add_column('users', sa.Column('telegram_chat_id', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('notify_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notify_enabled')
    op.drop_column('users', 'email')
    op.drop_column('users', 'telegram_chat_id')
    op.drop_index(op.f('ix_saved_searches_user_id'), table_name='saved_searches')
    op.drop_table('saved_searches')
    op.drop_index(op.f('ix_notification_logs_user_id'), table_name='notification_logs')
    op.drop_index('ix_notif_user_job_kind', table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_index('ix_applications_user_status', table_name='applications')
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index('ix_jobs_source_first_seen', table_name='jobs')
    op.drop_index(op.f('ix_jobs_source'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_function'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_is_remote'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_is_active'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_first_seen_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_district'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_deadline'), table_name='jobs')
    op.drop_index('ix_jobs_active_deadline', table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
